application: xsearch4hacker
version: 1
runtime: python
api_version: 1
threadsafe: yes
 
handlers:
- url: /styles
  static_dir: styles

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  #login: admin
 
- url: /.*
  script: main.py
  
builtins:
- remote_api: on  
